title: Geneticure
email: admin@geneticure.com
description: Geneticure reveals the right medication for you, prescribed by your DNA.
baseurl: ""
url: https://geneticure.com
twitter_username: geneticure
github_username: geneticure

sass:
  sass_dir: _sass
  style: expanded

kramdown:
  auto_ids: true
