baseurl: ""
company: Geneticure
company_long: Geneticure, Inc.
email: info@geneticure.com
description: Geneticure reveals the right medication for you, prescribed by your DNA.
github_username: geneticure
logo: /assets/img/logo.svg
portal:
  url: https://gcedev.herokuapp.com/
preview_img: /assets/img/site-preview.jpg
preview_img_alt: Geneticure logo
slogan: Medicine should be personalized.
tell_doc_url: mailto:YOUR DOCTOR'S EMAIL?cc=info@geneticure.com&?subject=I'm%20interested%20in%20this%20hypertension%20test&body=Hello!%20I%20came%20across%20Geneticure's%20hypertension%20test.%20It%20uses%20my%20DNA%20to%20figure%20out%20the%20high%20blood%20pressure%20treatment%20my%20body%20is%20most%20likely%20to%20respond%20to.%20Is%20this%20something%20we%20could%20try%3F%20You%20can%20read%20more%20and%20see%20their%20research%20at%20https%3A%2F%2Fgeneticure.com%0D%0A%0D%0AThank%20you!
title: Geneticure
twitter_username: geneticure
url: https://geneticure.com

contact:
  address:
    line_1: 4 3rd Street SW, Suite 305b
    city: Rochester
    state: MN
    zip: 55902
  phone:
    - 1.800.DNA.8109
    - 1.800.362.8109
  url: https://gcedev.herokuapp.com/contact

disclaimer: These statements have not been evaluated by the Food and Drug Administration. This product is not intended to diagnose, treat, cure, or prevent any disease. This test, like all medical tests, should be used by your healthcare provider as an aid in decision making about your health, which includes much more information than genetics. Do not start or stop taking any medications without first consulting your healthcare provider.

menu:
  - - text: About
      to: /
    - text: Sign in
      to: https://gcedev.herokuapp.com
    - text: Contact
      to: https://gcedev.herokuapp.com/contact
  - - text: FAQ
      to: /faq
    - text: Press
      to: /press
    - text: Research
      to: /research
    - text: Team
      to: /team
    - text: API
      to: /api
menu-legal:
  - text: Terms and conditions
    to: /terms
  - text: Privacy policy
    to: /privacy
menu-social:
  - text: LinkedIn
    to: https://linkedin.com/company/geneticure
  - text: Twitter
    to: https://twitter.com/geneticure

collections:
  pages:
    output: true
    permalink: /:path
excerpt_separator: <!--excerpt-->
kramdown:
  auto_ids: true
sass:
  sass_dir: _sass
  style: expanded
